import os

BLOCK_WIDTH = 1
BLOCK_HEIGHT = 1
TEXTURES_DIRECTORY = 'assets/textures'
OUTPUT_DIRECTORY = 'output'
GRASS_PALETTE = 'assets/grass.png'
FOLIAGE_PALETTE = 'assets/foliage.png'
BIOME_BLENDING = False

if not os.path.exists(OUTPUT_DIRECTORY):
    os.makedirs(OUTPUT_DIRECTORY)

FOLIAGE = {
    'minecraft:sugar_cane',
    'minecraft:vines',
    'minecraft:grass',
    'minecraft:tall_grass',
    'minecraft:lily_pad',
    'minecraft:pumpkin_stem',
    'minecraft:melon_stem'
}

BLACKLIST_BLOCKS = {
    'minecraft:bubble_column',
    'minecraft:air',
    'minecraft:cave_air',
    'minecraft:chest',
    'minecraft:green_banner',
    'minecraft:pink_banner',
    'minecraft:white_wall_banner',
    'minecraft:cyan_wall_banner',
    'minecraft:brown_wall_banner',
    'minecraft:grindstone',
    'minecraft:birch_wall_sign',
    'minecraft:oak_wall_sign',
    'minecraft:pink_bed',
    'minecraft:blue_bed',
    'minecraft:white_bed',
    'minecraft:yellow_bed',
    'minecraft:red_bed',
    'minecraft:orange_bed',
    'minecraft:potted_blue_orchid',
    'minecraft:potted_pink_tulip',
    'minecraft:potted_lily_of_the_valley',
    'minecraft:potted_poppy',
    'minecraft:potted_orange_tulip',
    'minecraft:potted_white_tulip',
    'minecraft:potted_oxeye_daisy',
    'minecraft:potted_azure_bluet',
    'minecraft:potted_cornflower',
    'minecraft:potted_dandelion',
    'minecraft:potted_oak_sapling',
    'minecraft:potted_red_mushroom',
    'minecraft:potted_spruce_sapling',
    'minecraft:purple_bed'
    'minecraft:birch_button',
    'minecraft:dark_oak_button',
    'minecraft:spruce_button',
    'minecraft:stone_button'
}

TRANSLATE_BLOCK_TO_TEXTURE = {
    'minecraft:tube_coral_wall_fan':'minecraft:tube_coral_fan',
    'minecraft:bubble_coral_wall_fan':'minecraft:bubble_coral_fan',
    'minecraft:horn_coral_wall_fan':'minecraft:horn_coral_fan',
    'minecraft:brain_coral_wall_fan':'minecraft:brain_coral_fan',
    'minecraft:fire_coral_wall_fan':'minecraft:fire_coral_fan',
    'minecraft:infested_stone':'minecraft:stone',
    'minecraft:wall_torch':'minecraft:torch',
    'minecraft:sweet_berry_bush':'minecraft:sweet_berry_bush_stage3',
    'minecraft:cobblestone_stairs':'minecraft:cobblestone',
    'minecraft:cobblestone_slab':'minecraft:cobblestone',
    'minecraft:wheat':'minecraft:wheat_stage7',
    'minecraft:oak_slab':'minecraft:oak_planks',
    'minecraft:oak_fence':'minecraft:oak_planks',
    'minecraft:oak_stairs':'minecraft:oak_planks',
    'minecraft:spruce_stairs':'minecraft:spruce_planks',
    'minecraft:spruce_slab':'minecraft:spruce_planks',
    'minecraft:dark_oak_slab':'minecraft:dark_oak_planks',
    'minecraft:dark_oak_stairs':'minecraft:dark_oak_planks',
    'minecraft:polished_andesite_slab':'minecraft:polished_andesite',
    'minecraft:birch_pressure_plate':'minecraft:birch_planks',
    'minecraft:oak_pressure_plate':'minecraft:oak_planks',
    'minecraft:spruce_fence':'minecraft:spruce_planks',
    'minecraft:birch_fence':'minecraft:birch_planks',
    'minecraft:birch_stairs':'minecraft:birch_planks',
    'minecraft:birch_slab':'minecraft:birch_planks',
    'minecraft:oak_fence_gate':'minecraft:oak_planks',
    'minecraft:birch_fence_gate':'minecraft:birch_planks',
    'minecraft:dark_oak_fence':'minecraft:dark_oak_planks',
    'minecraft:cobblestone_wall':'minecraft:cobblestone',
    'minecraft:bamboo':'minecraft:bamboo_stage0',
    'minecraft:sticky_piston':'minecraft:piston_top_sticky',
    'minecraft:redstone_wire':'minecraft:redstone_dust_dot',
    'minecraft:piston_head':'minecraft:piston',
    'minecraft:stone_slab':'minecraft:stone',
    'minecraft:smooth_stone_slab':'minecraft:smooth_stone',
    'minecraft:redstone_wall_torch':'minecraft:redstone_torch',
    'minecraft:dark_oak_wood':'minecraft:dark_oak_log',
    'minecraft:dispenser':'minecraft:dispenser_front',
    'minecraft:carrots':'minecraft:carrots_stage3',
    'minecraft:potatoes':'minecraft:potatoes_stage3',
    'minecraft:nether_wart':'minecraft:nether_wart_stage2',
    'minecraft:campfire':'minecraft:campfire_log_lit',
    'minecraft:sandstone_wall':'minecraft:sandstone',
    'minecraft:dropper':'minecraft:dropper_front',
    'minecraft:beehive':'minecraft:beehive_front_honey',
    'minecraft:sandstone_stairs':'minecraft:sandstone',
    'minecraft:fire':'minecraft:fire_0',
    'minecraft:jungle_stairs':'minecraft:jungle_planks',
    'minecraft:jungle_fence':'minecraft:jungle_planks',
    'minecraft:jungle_slab':'minecraft:jungle_planks',
    'minecraft:stone_brick_stairs':'minecraft:stone_bricks',
    'minecraft:acacia_fence':'minecraft:acacia_planks',
    'minecraft:acacia_stairs':'minecraft:acacia_planks',
    'minecraft:acacia_slab':'minecraft:acacia_planks',
    'minecraft:acacia_pressure_plate':'minecraft:acacia_planks',
    'minecraft:stone_pressure_plate':'minecraft:stone',
    'minecraft:acacia_wood':'minecraft:acacia_log',
    'minecraft:sandstone_slab':'minecraft:sandstone',
    'minecraft:acacia_fence_gate':'minecraft:acacia_planks',
    'minecraft:spruce_fence_gate':'minecraft:spruce_planks',
    'minecraft:stripped_oak_wood':'minecraft:stripped_oak_log',
    'minecraft:white_carpet':'minecraft:white_wool',
    'minecraft:yellow_carpet':'minecraft:yellow_wool',
    'minecraft:green_carpet':'minecraft:green_wool',
    'minecraft:beetroots':'minecraft:beetroots_stage3',
    'minecraft:snow_block':'minecraft:snow',
    'minecraft:infested_stone_bricks':'minecraft:stone_bricks',
    'minecraft:repeating_command_block':'minecraft:repeating_command_block_front',
    'minecraft:red_carpet':'minecraft:red_wool',
    'minecraft:stone_brick_slab':'minecraft:stone_bricks'
}